### PR TITLE
Ios10 notifications

### PR DESCRIPTION
**Pull request by MatthewGerber**

### CODE REVIEW

**Comment by MatthewGerber** [comment]
@mrucker @wesbonelli Here's the new callback notification architecture that accommodates pre- and post-10.0 iOS APIs. It compiles in iOS, but I haven't actually run any of the code. There are almost certainly bugs here, but it's a start and open for comments on implementation. Next steps:

* Determine whether this approach will support desired unit tests.
* Test all affected code on iOS 8.0, 8.2, and 10.0 (preferably physical devices).
* Once everything looks good, make necessary changes to the Android project. Since we're not actually changing the functionality of Android, this will be straightforward...just creating classes and moving methods.

**Comment by mrucker** [comment]
Your interfaces look a lot like the ones I had mocked up (see below) you just split out notification from callbacks. I'm moving all your code in now and starting from there.

```
        void OneTimeNotify(string message, string title);

        void RepeatingNotify(TimeSpan delay, TimeSpan repeat, string message, string title);

        string OneTimeCallback(TimeSpan interval, Action<string, CancellationToken, Action> callback);

        string RepeatingCallback(TimeSpan interval, bool leadingLag, Action<string, CancellationToken, Action> callback);
```

**Comment by MatthewGerber** [comment]
Glad to hear it. It's probably good to separate callbacks from notifications because they have separate use cases.

**Comment by mrucker** [comment]
Yeah, I couldn't decide. Conceptually I thought so too, but functionally I
didn't know if the API's allowed enough separation. You know better than me
so I'll keep going down that road.

**Comment by MatthewGerber** [comment]
Sensus callbacks and notifications boil down to the same iOS APIs, but I think it's useful to keep them separate...I think.

**Comment by MatthewGerber** [comment]
Confirming that f9cf9795338ffea7f814d0049986cbfdd9f883bd also fixes issues with notifications on iOS < 8.2.

On to Android.

**Pull request merged**
