### PR TITLE
bluetooth solution

### PR DESCRIPTION
**Pull request by bzd3y**
Fixing Sensus.sln

### CODE REVIEW

**Comment by Boukhechba** [comment]
@bzd3y  I don't see any commits related to the probe. Only one commit about Sensus.sln

**Comment by bzd3y** [comment]
Right, the other stuff already got pulled in with the last request. The only difference now is the solution file.

**Comment by Boukhechba** [comment]
@bzd3y I have reverted the other merge (#797 ). So could you please create a new pull request again from your previous bluetooth branch ?

**Comment by bzd3y** [comment]
I’ll see what I can do. If you reverted the original changes then our branches are probably out of sync and it might be tricky to get them back.

**Comment by Boukhechba** [comment]
@bzd3y you can simply create a new pull request from [your bluetooth branch], I can do that if you want.(https://github.com/bzd3y/sensus/tree/bluetooth)

**Comment by bzd3y** [comment]
That’s what I already did. But your branch is ahead of mine now since you merged those commits in and then reverted them. I’ll try rebasing onto a new branch and do a pull request from that one.

**Comment by bzd3y** [comment]
Okay, I just did a pull request that I think should fix the problem. You’ll see a change to Sensus.sln, but that’s me overwriting the bad one with a copy from your develop branch. So you shouldn’t see conflicts, but if you do, just take your entire file over mine when you merge. Let me know how this works.

**Pull request merged**
