### PR TITLE
Mms android

### PR DESCRIPTION
**Pull request by clmckinley**

### CODE REVIEW

**Comment by MatthewGerber** [comment]
@clmckinley Is this one done, too?

**Comment by MatthewGerber** [comment]
@clmckinley The following still does not seem to work:

1) Start protocol with SMS probe enabled.
2) Start a group text (select multiple recipients).
3) Send a text-only message.

The outgoing observer does not report a Datum.

Does the above work for you?

**Comment by clmckinley** [comment]
@MatthewGerber I followed the steps above and confirmed that this does work on my LG G6.

**Comment by clmckinley** [comment]
@MatthewGerber The steps above work on the group pixel phone.

The study i am using can be downloaded at https://github.com/clmckinley/sensus-studies/blob/master/txt%20message.json?raw=true

**Pull request merged**
