### PR TITLE
#852 probe refactor

### PR DESCRIPTION
**Pull request by bzd3y**
#852 @Boukhechba I'm doing a PR so you can look this over and see if there's anything I missed. Please wait to merge it, though, because I had to change the calendar probe quite a bit for this and because I don't think it actually worked correctly the way it was, so I want to make sure I got it working now. I'll add those commits to this PR when I'm done.

### CODE REVIEW

**Comment by Boukhechba** [comment]
This looks fine. There is some documentation missing in some parts (e.g. BluetoothDeviceProximityDatum.cs) but that's fine for now. I guess you can come back to it later.

**Comment by bzd3y** [comment]
@Boukhechba Sorry it took me a while to do this last push. I missed the Bluetooth probe but I just fixed that real quick. I also just pushed the calendar probe with documentation comments.

I noticed that the duration field of the Android calendar probe always has 0 because apparently that's just what Android stores. I didn't fix that to be calculated from the start and end times like it is on the iOS probe, but I can do that now or later. Also, the property type on the CalendarDatum is a double while other probes use TimeSpan for similar properties, but I'm not sure if you would want to change that.

**Comment by Boukhechba** [comment]
@bzd3y I am not sure about what you mean by "apparently that's just what Android stores". Could you please elaborate further ?

**Comment by bzd3y** [comment]
@Boukhechba Yes, sorry. I mean that the event has a 0 stored in that field in the calendar record. So when the datum is being created it is looking at all the fields to get the datum values and that is 0 even if end - start != 0. In the iOS probe the duration was already being calculated that way because there is no duration field at all. Does that make sense?

**Comment by Boukhechba** [comment]
@bzd3y Do you have a sense of how to fix this ? maybe you can loop Ryan in ?

**Pull request merged**
