### PR TITLE
bluetooth probe #781 #786

### PR DESCRIPTION
**Pull request by bzd3y**
Bluetooth probe #781 #786

### CODE REVIEW

**Comment by Boukhechba** [comment]
@bzd3y Can you please avoid committing changes to Sensus.sln and Sensus.Android.Shared.projitems. This creates conflicts when I merge with develop.

**Comment by bzd3y** [comment]
@Boukhechba I can try. I can probably avoid committing changes to the solution, sorry about that. But I don't know how I would do that for the project. The Sensus.Android.Shared.projitems change was a file that got added for this issue and if I didn't commit that then it wouldn't get merged into the project.

**Comment by Boukhechba** [comment]
@bzd3y  Can you please create a new pull request for this task without committing changes to Sensus.sln ? I wasn't able to merge your pull request properly.

**Comment by bzd3y** [comment]
I have a blank solution now in my bluetooth branch and don’t know what it is supposed to look like. Do you want it to look like https://github.com/predictive-technology-laboratory/sensus/blob/develop/Sensus.sln from the main repository?

**Comment by Boukhechba** [comment]
Yes

**Comment by bzd3y** [comment]
Okay, I did a new pull request. Hopefully that works.

**Pull request merged**
