### PR TITLE
783 add calendar probe

### PR DESCRIPTION
**Pull request by rd3fa**
added calendar probe

### CODE REVIEW

**Comment by Boukhechba** [comment]
@rd3fa Is this probe working on both Android and iOS ? How is it scheduled ?

**Comment by rd3fa** [comment]
@Boukhechba  it should be working on both platforms. Right now it follows the default polling. (sleep duration value of 5000 ms I believe) does that sound right? If this is not the case, should we set the default to milliseconds that equal a day for the sleep duration until the next poll? If we do that, it seems that you have to have the probe running for a whole day for it to ever get any data.

**Comment by Boukhechba** [comment]
@rd3fa What do you mean by "If we do that, it seems that you have to have the probe running for a whole day for it to ever get any data."

**Comment by rd3fa** [comment]
@Boukhechba @bzd3y  conflicts should be resolved

**Comment by Boukhechba** [comment]
@rd3fa It's not about conflicts, I usually manually resolve them. But, you have committed changes that might harm the current code, such as commits to Bluetooth probe and to iOS provisioning profile. (see files changed). We still have unwanted commits in the following files: 

Sensus.Android.Tests/Sensus.Android.Tests.csproj
Sensus.iOS/Info.plist
Sensus.iOS/Sensus.iOS.csproj
Sensus.Android.Shared/Probes/Context/AndroidBluetoothDeviceProximityProbe.cs

I am sorry about this, but if you have a better way of dealing with those unwanted commits, just let me know.

**Comment by rd3fa** [comment]
@Boukhechba  Ok my apologies. I will get these reverted today and re-sync

**Comment by rd3fa** [comment]
@Boukhechba  these conflicts should be resolved now completely.

**Pull request merged**
