### PR TITLE
SNS Prototype 2.0

### PR DESCRIPTION
**Pull request by jtb8vm**
- better shell script for sending notifications

NOTE:
- includes example API Key for google Firebase that has since been refreshed

MOVING FORWARD:
- will move towards AppCenter services on mobile client to register devices / handle notifications.
- will post guides on setting up SNS

### CODE REVIEW

**Comment by MatthewGerber** [comment]
@jtb8vm Does this follow the Xamarin.Forms guide for PN that we discussed?

**Comment by jtb8vm** [comment]
@MatthewGerber  not yet, will refactor to XF notification handling as my next item-- just returned from vacation and will be on this week.

**Comment by MatthewGerber** [comment]
@clmckinley https://docs.microsoft.com/en-us/appcenter/sdk/push/xamarin-forms -- this is what I think we need to do instead.

**Comment by MatthewGerber** [comment]
@jtb8vm Just a reminder:  this is what we should look into:

https://docs.microsoft.com/en-us/appcenter/sdk/push/xamarin-forms

This PR also needs to address #457.

**Pull request closed without merging**
