### PR TITLE
Cleaner Dependencies

### PR DESCRIPTION
**Pull request by mrucker**
Hey Prof. Gerber,

Here's the pull request with all the dependencies. You can see below that the HintPath is relative.

image

I found the ZipArchive reference I was missing. It was a Xamarin Component that I had to sign in to Xamarin to get.

Now all that I'm missing to get the project building is UnitTestingProtocol.json

image

image

I also have these "warnings". Because the warning is only trying to match against version number without the publicKeyToken I could also fix those warnings if I could get access to the source we built those libraries from. I'm fairly confident the mismatch is coming from the other Xamarin references having a dependency on these files and being built against the specific version mismatch.

image

### CODE REVIEW

**Comment by MatthewGerber** [comment]
Have you verified that XS will build using these changes?

Any particular reason for the underscore in "_Dependencies"? If not then do without to be in line with other directories (e.g., packages, Components, etc.).

There used to be a pre-build command that touched UnitTestingProtocol.json. This is for the Xamarin Test Cloud, which we aren't currently using. You can simply put an empty file there with that name.

**Comment by mrucker** [comment]
No I haven't had a chance to verify it will build in XS. That's why I wanted to look at it together. I don't have a mac or an OS X virtual machine, which means I don't have access to XS.

I do find it interesting that the Xamarin solution file marks its VS version as 2012. That was the last version of Visual Studio that I remember having the HintPath bug we were discussing. I wonder how much of Visual Studio is baked into XS? It would suggest to me that a deeper and longer partnership between Xamarin and Microsoft has existed than maybe I would have guessed.

The underscore is a naming convention from other projects I've worked on.  We certainly don't have to use it. It was just habit for me. It's primarily your project so I'll gladly adopt any conventions you prefer.

If you care to know why we used it on my old teams, for many of the old applications I supported it was common for there to be 20 or more projects in the solution (see below). My team chose to adopt the underscore convention to make the dependency folder stand out from the project files. We also liked that it flagged to future developers that there was something special about these dependencies compared to the packages folder. We took our inspirations from the .nuget file, but my old team didn't want to reuse the dot for fear of it looking like a system file.

image

I also just dropped in those empty files you suggested. Now VS is throwing out the errors below. Do they mean anything to you? Seems like an easy fix but I hate adding new dependencies without understanding. I'll go read the information URL they provide tomorrow.

image

**Comment by MatthewGerber** [comment]
Prof. Barnes has offered one of her iMacs for you to use. You can email her to get it, install XS, and test the build.

Let's go with no underscore.

I've seen your final errors before, but I can't recall how I fixed it. Check that Android is the active project and that you're building the Debug configuration.

**Comment by mrucker** [comment]
Cool. I'll try what you suggest and figure out the errors. I'll also get access to the iMac to verify the build.

**Comment by mrucker** [comment]
Alright,

I've got it building in XS. I still have a few niggling errors in VS that I'll work out this afternoon.

Here's what we have now:

- I've renamed the _Dependencies folder to dependencies.
- I removed Nuget.exe from the .nuget folder because there were issues with the hard coded mono paths in Nuget.targets. Also, both Xamarin and Microsoft recommend no longer including Nuget.exe in a Solution since auto packing importing is natively supported within XS and VS.
- I've verified that the dependency folder works relative to the solution in XS.
- I've verified that the VS 2015 solution template builds in XS

Let me know what questions you have or if you'd like me to change anything else.

Thanks

**Comment by mrucker** [comment]
I just pulled from source and resolved all the merge conflicts.

**Comment by MatthewGerber** [comment]
One thing I see is that `RestorePackages` has been removed. Is this no longer needed in order to automatically download packages that are missing locally?

**Comment by mrucker** [comment]
No, that was a tag that was part of the override restore. [Here](https://docs.nuget.org/consume/package-restore/migrating-to-automatic-package-restore) are the steps I followed when removing.

And the relevant step from that page for your question is:

image

**Pull request merged**
