### PR TITLE
Demons enhancements

### PR DESCRIPTION
**Pull request by MatthewGerber**

### CODE REVIEW

**Comment by MatthewGerber** [comment]
@wesbonelli I've updated your code for merge into my develop branch. Can you please test this to make sure it works for you? It should contain the same functionality, though I rearranged some things.

**Comment by wesbonelli** [comment]
@MatthewGerber Everything but the call duration trigger looks fine. I tested the trigger using both greater and greater than or equal to conditions, but the prompt did not fire in either case.

**Comment by MatthewGerber** [comment]
@wesbonelli This should work. Let me know.

**Comment by wesbonelli** [comment]
@MatthewGerber I think you've tested already, but in case not it is working now.

**Pull request merged**
