### PR TITLE
Added variable script scheduling interval

### PR DESCRIPTION
**Pull request by wesbonelli**

### CODE REVIEW

**Comment by MatthewGerber** [comment]
@wesbonelli Have you started coding the fix for delay overflow, or were those conversations with @mrucker just conceptual and not associated with any code?

**Comment by wesbonelli** [comment]
I've started, but it's all very unfinished (mismatching method signatures, etc, it won't compile yet). I left off working on it after we planned to meet in person.

I can add what I have to this PR if you'd like, but it's nowhere near commit-ready, even as a first draft at a solution.

**Comment by MatthewGerber** [comment]
I'd suggest putting those commits on another branch / PR and we can discuss.

**Comment by MatthewGerber** [comment]
@mrucker Can you please add some unit tests for this PR to `sensus/Sensus.Shared.Tests/Sensus.Shared/Probes/User/Scripts/ScheduleTriggerTests.cs` and/or `sensus/Sensus.Shared.Tests/Sensus.Shared/Probes/User/Scripts/ScheduleWindowTests.cs`? No rush.

**Comment by wesbonelli** [comment]
@MatthewGerber I won't have much of a chance to charge or use my computer this week, but I'll find an outlet tomorrow and make that PR.

**Pull request merged**
