### PR TITLE
Snooze

### PR DESCRIPTION
**Pull request by bzd3y**
Adding snoozed pause to protocols #779

### CODE REVIEW

**Comment by Boukhechba** [comment]
@rd3fa I just tested this feature and it doesn't seem to be working, at least not on Android. When I enable "Allow snooze", and start the protocol, I don't see snooze option on the protocol menu.

**Comment by bzd3y** [comment]
If AllowSnooze is set to true on the protocol (and AllowPause is also true) then when you click the Pause option, it gives you the option of either pausing like normal or snoozing. If AllowSnooze is not set to true then the pause option behaves like it did before any changes.

**Comment by Boukhechba** [comment]
@bzd3y  We might need to allow snooze only . So snooze should be separate from pause.

**Comment by bzd3y** [comment]
Okay, should I go ahead and make this change after I finish up my other stuff?

**Pull request merged**
