### PR TITLE
Surveys #796

### PR DESCRIPTION
**Pull request by bzd3y**
#796 I'm not completely sure that I was seeing the same problem this issue described (but I think I did fix a problem either way). It looks like this might not have been caused by a delay, but from an issue where when the survey notification is displayed after the app first starts up (like after being deployed, or forced to stop, etc.) and the user clicks the notification, the menu isn't hidden. So the survey page gets pushed onto the stack behind the menu and can't be seen and it looks like nothing happens. So I solved this by hiding the menu when the user clicks the notification, which is what happens when they click the menu options. If this doesn't solve the problem this issue is describing then let me know and I'll keep looking.

### CODE REVIEW

**Comment by Boukhechba** [comment]
Thanks for working on this. But that's not the problem that participants were complaining about. The surveys don't show up until a minute or so, it's not a menu problem because they do click on surveys button. It looks like during those times, the app is sending the data to S3. (Data sync progress is shown up)

**Comment by bzd3y** [comment]
Okay, I was afraid of that. So they click the notification and the survey list comes up and it is just empty for about a minute and then they appear? I can keep looking into that.

**Comment by bzd3y** [comment]
So is the sync to remote initiated by them clicking the survey button?

**Comment by Boukhechba** [comment]
I think the sync to remote is initiated by the fact that they open the app. Sync to remote is done periodically (every 4 hours), and needs the app to be on the foreground (iOS only). So what happens is that if they don't submit data in time, I think the data sync will be postponed until they open the app. If they open the app to answer a survey, the surveys will have to wait until syncing all data.

**Comment by bzd3y** [comment]
@Boukhechba I just added a new commit to #805 for #796

**Pull request merged**
