### PR TITLE
Input Copy Tests

### PR DESCRIPTION
**Pull request by mrucker**
Prof. Gerber,

Here are the tests. I found one really unexpected piece of behavior that might invalidate all our theories?

If you have a chance, take a look at the DisplayConditionInputCopyTest1() test. It appears to update references as long as the Input being referenced is inside our group? I've got a few more theories I'm going to test out around that behavior, but it is certainly not what I expected.

Thanks

### CODE REVIEW

**Comment by mrucker** [comment]
Alright,

I played around a little more with this code. Apparently JsonConvert maintains references within itself. That means if we run the serialize/deserialize at the collection level rather than on each individual input we can preserve references and all unit tests now pass except for case five with the DisplayCondition references an Input outside of the group.

I believe you said that the DisplayCondition sometimes does reference inputs outside of the group? If not then I think this might be the best solution? If it does then I think we'll still need to run with the original solution.

**Comment by MatthewGerber** [comment]
Yep, display conditions can reference other input groups. I think we either need to go back to using serialize/deserialize for the entire script, or do the reference update hack as I've currently got. Given the difficulty of the former and some advantages of copy constructors, I guess we'll go with the latter.

**Comment by MatthewGerber** [comment]
Yes, JSON.NET maintains all object references. This is why I like it for
copying versus copy constructors, but I see the benefits of each approach.
I think what we have now will work. It's a mix of copy constructors and
serialize/deserialize, which upsets the purist in me. But at this point I'd
rather not revert everything back to pure serialize/deserialize, and pure
copy constructor will also be more work.

**Comment by mrucker** [comment]
Yeah, I'm starting to come around. As I have mentioned, in industry, copy
constructors are preferred on projects over serializing/deserializing.
However, this assumption is obviously built on a lot of other architectural
conventions as well.

I think we only have two or three copy constructors. Changing back to all
Copy() methods wouldn't be very hard or risky in my opinion. I'd just write
several unit tests around the copy constructor to try and capture all
current behavior. Then I'd switch over to the Copy method and make sure the
tests still pass/behave as expected.

Also, in my mind, I think this decisions really hinges on how we ultimately
want to crack the protocol backwards compatibility nut.

**Comment by MatthewGerber** [comment]
Your final point is correct. We're going to need to figure out a different way to save/load protocols, which encompasses the task of saving/loading everything they contain (including input groups and inputs). However we end up doing that should take care of all copying considerations related to this PR as a side effect.

I'm comfortable sticking with what we have now, unless you have any remaining concerns.

**Comment by MatthewGerber** [comment]
Issue #271, for reference.

**Comment by mrucker** [comment]
I'm good with that too.

I've got some ideas I've been playing with in my head for the protocol
stuff if you want to have a conversation at some point about how we might
handle it. I'm not pushing this though. Just something that has been in my
head while doing other stuff.

**Comment by MatthewGerber** [comment]
Sure, put it on the agenda for our next meeting.

Matt

**Pull request merged**
